Simpleblog/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'about' => 'pages#about', as: 'about'

  resources :posts
end

Simpleblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Simpleblog/app/models/post.rb
class Post < ApplicationRecord
end

Simpleblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Simpleblog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = "About US";
    end
end

Simpleblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all 
    end

    def new
    end

    def show 
        @post = Post.find(params[:id])
    end

    def create
        @post = Post.new(post_params)

        @post.save
        redirect_to @post
    end


    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

Simpleblog/app/helpers/application_helper.rb
module ApplicationHelper
end

Simpleblog/app/helpers/pages_helper.rb
module PagesHelper
end

Simpleblog/app/helpers/posts_helper.rb
module PostsHelper
end

Simpleblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Simple Blog</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>           
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create Post", new_post_path %></li>           
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class='container'>
      <%= yield %>
    </div>
    
  </body>
</html>

Simpleblog/app/views/pages/about.html.erb
<h1><%= @title %></h1>

Simpleblog/app/views/posts/index.html.erb
<h1>BlogPosts</h1>
<% @posts.each do |post| %>
    <h3><%= post.body %></h3>
<% end %>    

Simpleblog/app/views/posts/new.html.erb
<h1>Add Posts</h1>

<%= form_for :post, url: posts_path do |f| %>
    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :body %>
        <%= f.text_field :body %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>
    
<% end %>

Simpleblog/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>